// Generated by CoffeeScript 2.0.3
var NullStream, events;

events = require('events');

module.exports = NullStream = (function() {
  class NullStream extends events.EventEmitter {
    pause() {}

    resume() {}

    pipe() {}

    write(data) {
      return this.emit('data', data);
    }

    end() {
      return this.emit('close');
    }

    // Shared API
    destroy() {}

    destroySoon() {}

  };

  // Readable Stream
  NullStream.prototype.readable = true;

  // Writable Stream
  NullStream.prototype.writable = true;

  return NullStream;

})();
