// Generated by CoffeeScript 2.0.3
var Response, pad, styles;

styles = require('./Styles');

pad = require('pad');

module.exports = Response = (function() {
  class Response extends styles {
    constructor(settings) {
      super(settings);
      this.shell = settings.shell;
    }

    prompt() {
      return this.shell.prompt();
    }

  };

  Response.prototype.pad = pad;

  return Response;

})();
