// Generated by CoffeeScript 2.0.3
var existsSync, fs, path;

fs = require('fs');

path = require('path');

existsSync = fs.existsSync || path.existsSync;

module.exports = {
  flatten: function(arr, ret) {
    var i, j, ref;
    if (ret == null) {
      ret = [];
    }
    for (i = j = 0, ref = arr.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (Array.isArray(arr[i])) {
        this.flatten(arr[i], ret);
      } else {
        ret.push(arr[i]);
      }
    }
    return ret;
  },
  // Discovery the project root directory or return null if undiscoverable
  workspace: function() {
    var dir, dirs, j, len;
    //dirs = require('module')._nodeModulePaths process.cwd()
    dirs = require('module')._nodeModulePaths(process.argv[1]);
    for (j = 0, len = dirs.length; j < len; j++) {
      dir = dirs[j];
      if (existsSync(dir) || existsSync(path.normalize(dir + '/../package.json'))) {
        return path.normalize(dir + '/..');
      }
    }
  },
  checkPort: function(port, host, callback) {
    var cmd;
    cmd = exec(`nc ${host} ${port} < /dev/null`);
    return cmd.on('exit', function(code) {
      if (code === 0) {
        return callback(true);
      }
      if (code === 1) {
        return callback(false);
      }
      return callback(new Error('The nc (or netcat) utility is required'));
    });
  }
};
